/**
 * Converts a Master Data JSON snapshot into seed SQL for Postgres.
 *
 * The JSON is whatever MasterData_Code.gs's doGet returns — i.e. exactly what
 * you already paste into the app today. Open the Apps Script Web App URL in a
 * browser tab, save the page as JSON, and run:
 *
 *   node scripts/json-to-sql.mjs master-data.json db/seed.sql
 *
 * (Pass the output path rather than using `>`: PowerShell redirects write
 * UTF-16, which psql rejects.)
 *
 * Then apply it with `npm run db:migrate:seed` (after db/schema.sql and db/ebdg.sql).
 *
 * WHY NOT JUST IMPORT THE CSVs: the sheet's data needs three fixes on the way
 * in, and doing them here means they're applied consistently and visibly
 * rather than by hand, 262 times:
 *   1. Contact_Number is a string in some rows and a number in others.
 *   2. 'Yes'/'No'/'' become real booleans — and a BLANK Active is reported,
 *      because blank silently means "inactive" and that revokes someone.
 *   3. Blank dates become NULL, not '' (Postgres rejects '' for a date).
 */

import { readFileSync, writeFileSync } from 'node:fs';

const file = process.argv[2];
const outFile = process.argv[3];
if (!file) {
  console.error('Usage: node scripts/json-to-sql.mjs <master-data.json> [output.sql]');
  process.exit(1);
}

/**
 * Read text regardless of how it was written. PowerShell's `>` redirect
 * produces UTF-16LE with a BOM, so a file created that way is not UTF-8
 * and JSON.parse fails on the very first character with an error that
 * points at the JSON rather than at the encoding. Sniff the BOM instead.
 */
function readText(path) {
  const buf = readFileSync(path);
  if (buf[0] === 0xff && buf[1] === 0xfe) return buf.toString('utf16le').slice(1);
  if (buf[0] === 0xfe && buf[1] === 0xff) return buf.swap16().toString('utf16le').slice(1);
  if (buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf) return buf.toString('utf8').slice(1);
  return buf.toString('utf8');
}

const raw = JSON.parse(readText(file));
const warnings = [];

/** Postgres string literal — doubles single quotes, or NULL when blank. */
const q = (v) => {
  if (v === null || v === undefined) return 'NULL';
  const str = String(v).trim();
  return str === '' ? 'NULL' : `'${str.replace(/'/g, "''")}'`;
};

/** 'Yes' -> true, anything else -> false. Blanks are flagged, not silently dropped. */
const bool = (v, { row, field, defaultTo = false }) => {
  const str = String(v ?? '').trim();
  if (str === '') {
    warnings.push(`  ${row}: ${field} is blank -> ${defaultTo} (blank is NOT 'Yes')`);
    return defaultTo;
  }
  return str === 'Yes';
};

/** Dates must be ISO or NULL — '' is a type error in Postgres, not an empty date. */
const date = (v) => {
  const str = String(v ?? '').trim();
  if (!str) return 'NULL';
  const iso = str.match(/^\d{4}-\d{2}-\d{2}$/) ? str : new Date(str).toISOString().slice(0, 10);
  return `'${iso}'`;
};

const num = (v) => {
  const str = String(v ?? '').trim();
  return str === '' || Number.isNaN(Number(str)) ? 'NULL' : String(Number(str));
};

const lines = [];
lines.push('-- Generated by scripts/json-to-sql.mjs — do not edit by hand.');
lines.push(`-- Source snapshot: ${raw.generatedAt ?? 'unknown'}`);
lines.push('begin;');
lines.push('');

// --- Site_Master first: poc_master.site_code references it -----------------
const sites = raw.siteMaster ?? [];
lines.push(`-- Site_Master (${sites.length} rows)`);
for (const r of sites) {
  if (!r.Site_Code) continue;
  lines.push(
    `insert into site_master (site_code, wh_code, facility_name, sap_code, cost_center, zone, state, city, address, pincode, channel, entity, business_type, gstin, lat_long, map_link, services_enabled, go_live_date, closure_date, is_active) values (` +
      [
        q(r.Site_Code), q(r.WH_Code), q(r.Facility_Name), q(r.SAP_Code), q(r.Cost_Center),
        q(r.Zone), q(r.State), q(r.City), q(r.Address), q(r.Pincode), q(r.Channel),
        q(r.Entity), q(r.Business_Type), q(r.GSTIN), q(r.Lat_Long), q(r.Map_Link),
        q(r.Services_Enabled || 'ALL'), date(r.Go_Live_Date), date(r.Closure_Date),
        bool(r.Active, { row: r.Site_Code, field: 'Active', defaultTo: true })
      ].join(', ') +
      `) on conflict (site_code) do nothing;`
  );
}
lines.push('');

// --- Service_Registry ------------------------------------------------------
const services = raw.serviceRegistry ?? [];
lines.push(`-- Service_Registry (${services.length} rows)`);
for (const r of services) {
  if (!r.Service_Code) continue;
  lines.push(
    `insert into service_registry (service_code, service_name, needs_approval, needs_delivery_validation, requires_evidence, cadence, submission_window, sla_hours, appscript_url, records_tab, audit_tab, is_active) values (` +
      [
        q(r.Service_Code), q(r.Service_Name),
        bool(r.Needs_Approval, { row: r.Service_Code, field: 'Needs_Approval' }),
        bool(r.Needs_Delivery_Validation, { row: r.Service_Code, field: 'Needs_Delivery_Validation' }),
        bool(r.Requires_Evidence, { row: r.Service_Code, field: 'Requires_Evidence' }),
        q(r.Cadence), q(r.Submission_Window), num(r.SLA_Hours),
        q(r.AppScript_URL ?? r.Spreadsheet_ID),
        q(r.Records_Tab || 'Records'), q(r.Audit_Tab || 'Audit'),
        bool(r.Active, { row: r.Service_Code, field: 'Active', defaultTo: true })
      ].join(', ') +
      `) on conflict (service_code) do nothing;`
  );
}
lines.push('');

// --- POC_Master -----------------------------------------------------------
const pocs = raw.pocMaster ?? [];
const knownSites = new Set(sites.map((r) => r.Site_Code).filter(Boolean));
lines.push(`-- POC_Master (${pocs.length} rows)`);
for (const r of pocs) {
  if (!r.Access_ID) continue;

  const siteCode = String(r.Site_Code ?? '').trim() || 'ALL';
  if (siteCode !== 'ALL' && knownSites.size > 0 && !knownSites.has(siteCode)) {
    warnings.push(`  ${r.Access_ID}: Site_Code '${siteCode}' has no Site_Master row — the FK will reject this`);
  }

  lines.push(
    `insert into poc_master (access_id, poc_email, poc_name, wh_code, role, site_code, service_codes, contact_number, is_primary, is_active, access_start_date, access_end_date, description, reporting_manager_email) values (` +
      [
        q(r.Access_ID), q(String(r.POC_Email ?? '').toLowerCase()), q(r.POC_Name), q(r.WH_Code),
        q(r.Role || 'SITE_POC'), q(siteCode), q(r.Service_Codes || 'ALL'),
        q(r.Contact_Number), // q() stringifies, so numeric phone numbers land as text
        bool(r.Is_Primary, { row: r.Access_ID, field: 'Is_Primary', defaultTo: true }),
        bool(r.Active, { row: r.Access_ID, field: 'Active', defaultTo: false }),
        date(r.Access_Start_Date), date(r.Access_End_Date),
        q(r.Description), q(r.Reporting_Manager_Email)
      ].join(', ') +
      `) on conflict (access_id) do nothing;`
  );
}

lines.push('');
lines.push('commit;');

// As above: write it ourselves so the shell never gets to choose an
// encoding. psql reads UTF-8; a UTF-16 .sql file fails just as opaquely.
if (outFile) {
  writeFileSync(outFile, lines.join('\n'), 'utf8');
  console.error(`Wrote ${outFile} (${lines.length} lines)`);
} else {
  console.log(lines.join('\n'));
}

if (warnings.length) {
  console.error(`\n-- ${warnings.length} thing(s) worth checking before you run this:`);
  console.error(warnings.join('\n'));
  console.error(
    '\n-- Blank Active values default to inactive, which revokes that person.\n' +
    '-- Fix them in the sheet and re-export if that is not what you want.'
  );
}
